# Compose used for development
# This file is needed because volumes are appended on override.
# So prod would also have dev's volumes, what should not happen.

version: '3.5'

services:
  frontend:
    build: .
    container_name: frontend_auth_dev
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - "8080:8080"

networks:
  default:
    name: dc-auth
