# Compose used for development
# This file is needed because volumes are appended on override.
# So prod would also have dev's volumes, what should not happen.

version: '3.5'

services:
  frontend:
    build:
      context: ${FRONTEND_PATH:-.}
      dockerfile: ./Dockerfile
    image:  dc-auth/frontend-auth-dev
    container_name: frontend_auth_dev
    tty: true
    volumes:
      - ${FRONTEND_PATH:-.}/src:/app/src
      - ${FRONTEND_PATH:-.}/public:/app/public
    ports:
      - "8080:8080"

networks:
  default:
    name: dc-auth
