language: node_js
node_js:
  - "8.11.4"
  - "node"
env:
  - WEBPACK_VERSION= # Current, from package.json
  - WEBPACK_VERSION=4
install:
  - cd client
  - yarn install
  - cd ..
stages:
  - lint
  - build
jobs:
  include:
    - stage: lint
      script:
        - cd client
        - yarn run lint
        - cd ..
    - stage: build
      script:
        - cd client
        - yarn run build
        - cd ..