language: node_js
node_js:
  - "8.6.0"
  - "node"
env:
  - WEBPACK_VERSION= # Current, from package.json
  - WEBPACK_VERSION=4
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
stages:
  - lint
  - test
  - build
jobs:
  include:
    - stage: lint
      script:
        # Run linter
        - yarn run lint
    - stage: test
      script:
        # Run tests
        - yarn run test
    - stage: build
      script:
        - yarn run build