language: node_js
node_js:
  - "8.6.0"
  - "node"
env:
  - WEBPACK_VERSION= # Current, from package.json
  - WEBPACK_VERSION=4
install:
  - yarn install
stages:
  - lint
  - test
  - build
jobs:
  include:
    - stage: lint
      script:
        - cd client
        - yarn run lint
    - stage: test
      script:
        - cd client
        - yarn run test
    - stage: build
      script:
        - cd client
        - yarn run build