language: node_js
node_js:
  - "8.11.4"
env:
  - WEBPACK_VERSION=4
install:
  - cd client
  - yarn install
  - cd ../server
  - yarn install
  - cd ..
stages:
  - lint
  - build
jobs:
  include:
    - stage: lint
      script:
        - cd client
        - yarn run lint
        - cd ..
    - stage: test
      script:
        - cd server
        - yarn run test
        - cd ..
    - stage: build
      script:
        - cd client
        - yarn run build
        - cd ..